# Built in style sets
export STYLE_SET_DEFAULT_H1=('<fg:cyan+>' '</fg>')
export STYLE_SET_DEFAULT_H2=('<fg:yellow+>' '</fg>')
export STYLE_SET_DEFAULT_H3=('<fg:magenta>' '</fg>')
export STYLE_SET_DEFAULT_H4=('<fg:white+>' '</fg>')

export STYLE_SET_DEFAULT_EM1=('<i>' '</i>')                             # *text*
export STYLE_SET_DEFAULT_EM2=('<b>' '</b>')                             # **text**
export STYLE_SET_DEFAULT_EM3=('<i><b>' '</b></i>')                      # ***text***
export STYLE_SET_DEFAULT_CODE=('<bg:black+><fg:green>' '</fg></bg>')   # `code`
